name: CMDbox
author: AlphaFarFar - vYN
description: Gives you everyting you need! changing this
version: 0.1
website: http://homiecraft.org
main: com.CMDbox.CMDbox

commands:
   mute:
      description: Mutes/unmutes a player
      permission: CMDbox.mute
      usage: /mute <player>
   tp:
      description: Teleports you to a player
      permission: CMDbox.tp
      usage: /tp <player>
   tphere:
      description: Teleports a player to you
      permission: CMDbox.tphere
      usage: /tphere <player>
   ban:
      description: Bans player
      permissions: CMDbox.ban
      usage: /ban <player>
   unban:
      descitption: Unbans banned player
      permissions: CMDbox.Unban
      usage: /unabn <player>
   kick:
      description: Kicks player from the server
      permissions: CMDbox.Kick
      usage: /kick <player>
   setwarp:
      description: Sets a warp at your location
      permissions: CMDbox.setwarp
      usage: /setwarp <warpName>
   warp:
      description: Warps to a warp xD
      permissions: CMDbox.warp
      usage: /warp <warpName>
   delwarp:
      description: Delete a warp!
      permissions: CMDbox.delwarp
      usage: /delwarp <warpName>
   God:
      description: Makes player take no damage.
      permissions: CMDbox.God
      usage: /god <player>
   Item:
      description: Gives player item.
      permissions: CMDbox.Item
      usage: /item <item ID> 
   cmdbox:
      description: Information about CMDbox
      usage: /cmdbox
      