name: CMDbox
author: AlphaFarFar - vYN
version: 0.1
main: com.CMDbox.CMDbox

commands:
   mute:
      description: Mutes/unmutes a player
      permission: CMDbox.mute
      usage: /mute <player>
   tp:
      description: Teleports you to a player
      permission: CMDbox.tp
      usage: /tp <player>
   tphere:
      description: Teleports a player to you
      permission: CMDbox.tphere
      usage: /tphere <player>
   ban:
      description: Bans player
      permissions: CMDbox.ban
      usage: /ban <player>
   unban:
      descitption: Unbans banned player
      permissions: CMDbox.Unban
      usage: /unabn <player>